In [16]:
import pandas as pd
import numpy as np

In [26]:
Teen_data = pd.read_csv("Teen_Mental_Health_Dataset.csv")

In [27]:
Teen_data = Teen_data.drop('platform_usage', axis=1)
Teen_data['gender'] = Teen_data['gender'].map({'male': 1, 'female':0})
Teen_data

,age,gender,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,1,7.9,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,0,1.9,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,0,1.3,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,1,7.4,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,0,4.7,4.9,3.0,2.37,1.4,medium,3,5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,0,6.8,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,1,2.3,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,0,1.7,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,1,3.9,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,0,4.7,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [28]:
Teen_data['social_interaction_level'] = Teen_data['social_interaction_level'].map({'low':0, 'medium':1, 'high':2})
Teen_data

,age,gender,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,1,7.9,7.4,2.9,3.01,1.5,0,2,2,1,0
1,19,0,1.9,8.0,2.9,3.22,0.8,2,8,1,10,0
2,17,0,1.3,7.6,0.5,3.92,0.0,2,2,4,2,0
3,15,1,7.4,6.9,1.6,3.48,0.8,1,1,7,9,0
4,15,0,4.7,4.9,3.0,2.37,1.4,1,3,5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,0,6.8,6.6,2.0,2.76,1.0,0,3,4,4,0
1196,16,1,2.3,8.0,1.9,2.12,0.4,2,7,4,4,0
1197,14,0,1.7,8.7,0.7,3.98,0.8,2,1,1,1,0
1198,15,1,3.9,8.5,2.1,3.19,0.6,2,7,9,9,0
1199,16,0,4.7,6.5,1.0,2.91,0.9,1,5,7,3,0

In [6]:
Teen_data.describe()

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,15.928333,4.536667,6.449417,1.740333,2.990383,1.014500,5.445833,5.636667,5.565000,0.025833
std,2.021947,2.029599,1.442677,0.716660,0.576758,0.582185,2.903290,2.859453,2.830627,0.158704
min,13.000000,1.000000,4.000000,0.500000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,14.000000,2.800000,5.200000,1.100000,2.500000,0.500000,3.000000,3.000000,3.000000,0.000000
50%,16.000000,4.500000,6.500000,1.800000,2.990000,1.000000,5.000000,6.000000,6.000000,0.000000
75%,18.000000,6.300000,7.600000,2.400000,3.480000,1.500000,8.000000,8.000000,8.000000,0.000000
max,19.000000,8.000000,9.000000,3.000000,4.000000,2.000000,10.000000,10.000000,10.000000,1.000000

In [30]:
X = Teen_data.drop("depression_label", axis=1)
y = Teen_data["depression_label"]

In [42]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import plot_tree
model = LinearRegression()

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.80)

model.fit(X_train, y_train)

plt.figure(figsize=(15,7))
plot_tree(model.estimators_[0], feature_names=teen_data.feature_names, class_names=teen_data.target_names, filled=True)

AttributeError: 'LinearRegression' object has no attribute 'estimators_'

In [39]:
valuation = model.score(X_test, y_test)
valuation

0.08920834393091326